---
- name: Update all packages to the latest version # noqa package-latest
  ansible.builtin.dnf:
    name: "*"
    state: latest

- name: Install base required packages
  ansible.builtin.dnf:
    name:
      - git
      - g++
      - python3
      - python3-devel
    state: present

- name: Add user to the Docker group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true
