---
- name: Update all packages to the latest version # noqa package-latest
  ansible.builtin.dnf:
    name: "*"
    state: latest

- name: Install base required packages
  ansible.builtin.dnf:
    name:
      - g++
      - python3
      - python3-devel
    state: present
