# Description: This file is used to deploy the UI stack on the bot node.
# It assumes that the gobot and redis is already deployed on the bot node.
- name: Deploy UI stack on bot node
  hosts: botNode
  roles:
    - role: geerlingguy.docker
      become: true
    - role: packages
      become: true
    - role: nexodus
      become: true
    - role: ui
      become: true
  vars_files:
    - vars.yml
  environment:
    API_USER: "${API_USER:-<username>}"
    API_PASS: "${API_PASS:-<password>}"
