- name: Deploy EC2 Instuct Lab Bot Node
  hosts: localhost
  vars_files:
    - vars.yml
  roles:
    - role: ec2
      vars:
        ec2_aws_instance_type: t2.xlarge
        ec2_aws_nodetype_tag: "instructlab-bot-node"
