version: "3.4"

services:
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379

  bot:
    container_name: bot
    image: quay.io/instruct-lab-bot/bot:latest
    depends_on:
      - redis
    ports:
      - 8000:3000
    environment:
      - APP_ID=${APP_ID}
      - LOG_LEVEL=${LOG_LEVEL}
      - PRIVATE_KEY=${PRIVATE_KEY}
      - REDIS_URL=redis://redis:6379
      - WEBHOOK_PROXY_URL=${WEBHOOK_PROXY_URL}
