---
- name: Install base required packages
  ansible.builtin.dnf:
    name:
      - dnf-plugins-core
      - podman
      - git
      - g++
      - python3
      - python3-devel
    update_cache: true
    state: present
  become: true

- name: Installing podman
  ansible.builtin.package:
    name: "podman"
    state: present
  become: true
