version: "3.4"

services:
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379

  bot:
    container_name: bot
    image: ghcr.io/instructlab/instructlab-bot/instructlab-gobot:main
    env_file:
      - ../../.env
    depends_on:
      - redis

  worker-test:
    container_name: worker-test
    image: ghcr.io/instructlab/instructlab-bot/instructlab-serve:main
    depends_on:
      - redis
    env_file:
      - ../../.env
    command:
      [
        "/instructlab-bot-worker",
        "--test",
        "--redis",
        "redis:6379",
        "generate",
      ]
