---
- name: Clone the bot repo  # noqa latest[git]
  ansible.builtin.git:
    clone: true
    repo: "https://{{ qa_github_token }}@github.com/instructlab/instructlab-bot.git"
    dest: /home/{{ ansible_user }}/instructlab-bot

- name: Build worker image
  containers.podman.podman_image:
    build:
      path: "/home/{{ ansible_user }}/instructlab-bot/worker"
      buildargs:
        GITHUB_USER: "{{ qa_github_uid }}"
        GITHUB_TOKEN: "{{ qa_github_token }}"
    name: "ghcr.io/instructlab/instructlab-bot/instructlab-serve"
    tag: "main"
    source: build

- name: List container images
  ansible.builtin.command:
    cmd: podman image ls
  register: ls_images
  changed_when: false

- name: Print the output of images listing
  ansible.builtin.debug:
    var: ls_images.stdout_lines

- name: Start the worker
  containers.podman.podman_container:
    name: instruct_lab_worker
    image: "ghcr.io/instructlab/instructlab-bot/instructlab-serve:main"
    command: /bin/bash
    tty: true
    detach: true
    volumes:
      - "/home/fedora/instructlab:/data:Z"
    gpu_devices:
      - all

- name: List all containers
  ansible.builtin.command:
    cmd: podman ps -a
  register: ps_output
  changed_when: false

- name: Pause for 30 seconds before listing
  ansible.builtin.pause:
    seconds: 30

- name: Print the output of the container listing
  ansible.builtin.debug:
    var: ps_output.stdout_lines
