---
- name: Log into GHCR
  community.docker.docker_login:
    registry_url: ghcr.io
    username: instruct-lab-bot
    password: "{{ github_token }}"
    reauthorize: true

- name: Get container info
  community.docker.docker_container_info:
    name: redis
  register: redis_info

- name: Start the container
  community.docker.docker_container:
    name: instruct-lab-bot
    image: ghcr.io/redhat-et/instruct-lab-bot/instruct-lab-bot:main
    state: started
    pull: always
    env:
      APP_ID: "{{ app_id }}"
      PRIVATE_KEY: "{{ private_key }}"
      WEBHOOK_SECRET: "{{ webhook_secret }}"
      REDIS_URL: "redis://{{ redis_info.container.NetworkSettings.IPAddress }}:6379"
      WEBHOOK_PROXY_URL: "{{ webhook_proxy_url }}"
