name: build

on:
  push:
    branches: ["main"]

jobs:
  build:
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
        goarch: ["amd64", "arm64"]
    runs-on: ${{ matrix.os }}
    env:
      GOARCH: ${{ matrix.goarch }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.21"
          cache: false
      - name: Unit Tests
        if: matrix.goarch != 'arm64'
        run: |
          go test -v -coverprofile=profile.cov ./...
        working-directory: ./worker
      - id: build
        run: |
          go build -o "worker_$(go env GOOS)_${GOARCH}" main.go
          echo bin="worker_$(go env GOOS)_${GOARCH}" >> "$GITHUB_OUTPUT"
        working-directory: ./worker
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.build.outputs.bin }}
          path: worker/${{ steps.build.outputs.bin }}
